strategy:
  matrix:
    Mac:
      imageName: 'macos-10.13'
    Linux:
      imageName: 'ubuntu-16.04'
    Windows:
      imageName: 'vs2017-win2016'
      rustup_toolchain: stable
      working_directory: .

pool:
  vmImage: $(imageName)

steps:
  - script: rustup component add clippy rustfmt
    displayName: install clipppy and rustfmt

  - script: cargo fmt --all -- --check
    displayName: rustfmt
  - script: cargo build --all-features
    displayName: Cargo build
  - script: cargo clippy --all-features -- -D warnings
    displayName: clippy
  - script: cargo test --all-features
    displayName: Cargo test